### PR TITLE
Small correction to avoid links with multiple slashes

### PR DESCRIPTION
**Pull request by BobyTS**
Simple modification because several pages has double slash which caused client-side errors (concerning badges for example)

> Exemple : ${url.prefix}/habbo-imaging/badge/%imagerdata%.gif
> Before : http://localhost//habbo-imaging/badge/%imagerdata%.gif
> Now : http://localhost/habbo-imaging/badge/%imagerdata%.gif

I know that the correction could be applied to the variables but I prefer a faithful integration to Habbo

### CODE REVIEW

**Comment by sant0ro** [comment]
Many Thanks, Boby!

**Comment by s150217754** [comment]
Nice! Wanted to do this small correction during my free time and you've beat me to it :)

**Comment by sant0ro** [comment]
@s150217754 does you found any other bug during usage of Chocolatey? Can you test all features again?

**Comment by BobyTS** [comment]
@sant0ro Do you have something new about issue #147 ?

**Comment by s150217754** [comment]
@sant0ro Found some small little "bugs" and made some commits on development branch.

As for features, I didn't managed to test out all features yet. Will probably test out all of the features during next release which includes the StyleCI changes (hopefully it doesn't break any code).

**Comment by sant0ro** [comment]
Okay @s150217754 can you create a Pull Request with those changes?

**Comment by s150217754** [comment]
@sant0ro Its already committed on the development branch already. You can PR to master or binaries to effect the change.

**Comment by sant0ro** [comment]
Can you reference the PR?

**Comment by s150217754** [comment]
It's committed directly to the development branch without PR request. 

You can take a look at the commit logs of the development branch.

**Comment by sant0ro** [comment]
Okay I merged master into binaries.

**Pull request merged**
