### PR TITLE
CloudFlare IP Address Workarounds

### PR DESCRIPTION
**Pull request by airilx96**
Few fixes on users IP Address logging when server is using CloudFlare, IP Address of CloudFlare is logged instead of users real IP Address.

### CODE REVIEW

**Comment by sant0ro** [comment]
I think something is wrong in your commits. TravisCI Build it's saying that exists a bug.

**Comment by sant0ro** [comment]
See what the TravisCI build log says. He says that cannot find the CloudFlareHelper.php

Check for case sensivity.

**Comment by airilx96** [comment]
Hi, sorry for making too much changes. I've moved the fix files into /app/Helpers directory, as composer.json is having issues in detecting files in /app/ directory

**Comment by sant0ro** [comment]
All checks passed.

Merging.

**Comment by sant0ro** [comment]
Thanks for the contribution.

**Pull request merged**
